### ISSUE TITLE
The format of Input VCF files

### ISSUE THREAD

**Issue by YiBenqiu** [JiaoLab2021/EVG#1]
Hello, I would like to ask a question about the input VCF file. In PanGenie, there are very specific format requirements for the input VCF file. I've looked at the EVG logic flow. If the input VCF file does not meet PanGenie's format requirements, will EVG not call PanGenie?
![微信图片_20230925085653](https://github.com/JiaoLab2021/EVG/assets/57091259/411913e0-19a4-49a4-ab7f-7edf7cc82845)

**Comment by duzezhen** [comment]
EVG performs format conversion on the input VCF file using the "`graphvcf convert`" command to make it compatible with downstream software. Therefore, the format is not the determining factor for calling PanGenie. If you specifically want to call PanGenie, you can use the "--software" option to specify the desired software.

Wishing you good luck! Feel free to ask if you have any further questions.

**Comment by duzezhen** [comment]
In the latest version of `PanGenie`, if the previous variant's end position is after the current variant's start position, `PanGenie` will throw an error and exit. However, in `EVG v1.0.6`, when calling `PanGenie`, these variants will be ignored. Therefore, even if your VCF file does not meet the requirements of `PanGenie`, `EVG` can still run it without issues.
