### ISSUE TITLE
The fasta file is wrong, please check the parameters

### ISSUE THREAD

**Issue by YiBenqiu** [JiaoLab2021/EVG#2]
Description:

I'm encountering an issue when running the following command:
```EVG -r /BIGDATA2/scau_jyang_2/genome/Homo_sapiens.GRCh38.dna.toplevel.fa -v /BIGDATA2/scau_jyang_2/genome/pav-panel-freeze3.vcf.gz -s /BIGDATA2/scau_jyang_2/genome/sample.txt --mode  precise --threads 23 --jobs 3 --force &> /BIGDATA2/scau_jyang_2/genome/log.txt```

The error message I'm receiving is:
```[2023-10-07 21:47:42,175] [EVG.fasta_count] CMD: /BIGDATA2/scau_jyang_2/bio_software/EVG/fastAQ count -i /BIGDATA2/scau_jyang_2/genome/Homo_sapiens.GRCh38.dna.toplevel.fa```
```[EVG.fasta_count] The fasta file is wrong, please check the parameters.```

However, when I run this command separately, it works:
```/BIGDATA2/scau_jyang_2/bio_software/EVG/fastAQ count -i /BIGDATA2/scau_jyang_2/genome/Homo_sapiens.GRCh38.dna.toplevel.fa```

```[main::2023-10-07 21:49:27] You are using fastAQ (v1.0.6)```
```[main_count::2023-10-07 21:49:27] Running ...```
```readBase:3291585349```
```readNum:706```
```readLen:4662302```
```[main_count::2023-10-07 21:49:36] Done ...```

I'm using Python version 3.9. My Python environment details are as follows:
```python3: /BIGDATA2/scau_jyang_2/.conda/envs/evg_env/bin/python3.9-config /BIGDATA2/scau_jyang_2/.conda/envs/evg_env/bin/python3 /BIGDATA2/scau_jyang_2/.conda/envs/evg_env/bin/python3.9 /BIGDATA1/app/anaconda3/2020.07/bin/python3.8 /BIGDATA1/app/anaconda3/2020.07/bin/python3 /BIGDATA1/app/anaconda3/2020.07/bin/python3.8-config```

I am confused by this issue and would appreciate any guidance on how to resolve it.

**Comment by duzezhen** [comment]
`EVG` may not be able to read the result file of `fastAQ count` because `EVG` outputs the generated file in `/tmp` or `/var/tmp`, which may have restricted access permissions. You can check if you have permission to access these directories.

To modify the default output path for temporary files, you can use the following commands:

```
tmpn=`mktemp -u XXXXX`
tmpd="${tmpn}"
mkdir ${tmpd}
echo ${tmpd}
export TMP=${tmpd}
```

By executing these commands, you can set a different temporary file directory. This might resolve the issue you are facing.

Please try this solution, and if it indeed solves the problem, we will fix this bug in the next version.

Thank you very much for using our software and bringing up this issue.

**Comment by duzezhen** [comment]
Alternatively, you can try running the test data to see if it works.

If it's not due to temporary directory issues, you can send us the reference genome for testing.

Best wishes to you!

**Comment by YiBenqiu** [comment]
Thank you for your prompt response. I tried your suggestion, but unfortunately, it didn't resolve the issue. However, I managed to resolve the error by reinstalling the EVG software.

Now, when I attempt to run the test data using the following command:
```
#!/bin/bash

# Job name:
#SBATCH --job-name=EVG.sbatch
# Number of nodes needed for use case:
#SBATCH --nodes=1
#

# Processors per task:
#SBATCH --cpus-per-task=24
#
# Memory per node:
#SBATCH --mem=62G
#SBATCH --output=EVG.out
#SBATCH --error=EVG.err

source /BIGDATA2/scau_jyang_1/software/evg_env/bin/activate
module load gcc/7.4.0
cd /BIGDATA2/scau_jyang_1/software/EVG-main/test
EVG -r test.fa -v test.vcf.gz -s sample.txt --software VG-MAP VG-Giraffe GraphAligner Paragraph BayesTyper GraphTyper2 PanGenie --force  &>log.txt &
wait
```
I encounter the following error:
```
Files and parameters used:
-a	0
-c	0
-d	0
-e	3000000000
-g	0
-i	/BIGDATA2/scau_jyang_1/software/EVG-main/test/genotype/PanGenie/test1/test1.fq
-j	10
-k	31
-o	test1
-p	0
-r	/BIGDATA2/scau_jyang_1/software/EVG-main/test/convert/convert.test.fa
-s	test1
-t	10
-u	0
-v	/BIGDATA2/scau_jyang_1/software/EVG-main/test/genotype/PanGenie/test1/test1.vcf
Determine allele sequences ...
Found 1 chromosome(s) from the reference file.
Identified 769 variants in total from VCF-file.
#### Memory usage until now: 0.009004 GB ####
Write path segments to file: test1_path_segments.fasta ...
Found 1 chromosome(s) in the VCF.
#### Memory usage until now: 0.009004 GB ####
Count kmers in reads ...
Histogram peak: 1 (3323)
Computed kmer abundance peak: 1
Count kmers in genome ...
terminate called after throwing an instance of 'jellyfish::large_hash::array_base<jellyfish::mer_dna_ns::mer_base_static<unsigned long, 0>, unsigned long, atomic::gcc, jellyfish::large_hash::unbounded_array<jellyfish::mer_dna_ns::mer_base_static<unsigned long, 0>, unsigned long, atomic::gcc, allocators::mmap> >::ErrorAllocation'
  what():  Failed to allocate 17333333368 bytes of memory.
  ```
The full information is available in the EVG.log: 
[EVG.log.txt](https://github.com/JiaoLab2021/EVG/files/12852357/EVG.log.txt)
It appears that there is a memory overflow when running PanGenie with a single command in EVG pepline.

When I run PanGenie separately using the command:
 ```
  PanGenie -i <(zcat ${input}/test1.sim1.fq.gz ${input}/test1.sim2.fq.gz) -v /BIGDATA2/scau_jyang_1/software/EVG-main/test/genotype/PanGenie/test1/test1.vcf -r ${input}/test.fa -s test1 -j 23 -t 23
```
It works without any issues. I have also included the PanGenie log file: 
[PanGenie.log](https://github.com/JiaoLab2021/EVG/files/12852416/PanGenie.log)

```
#### Memory usage until now: 48.4737 GB ####
#### Memory usage until now: 48.4737 GB ####
Sampled 1 subset(s) of paths each of size 3 for genotyping.
#### Memory usage until now: 48.4737 GB ####
Construct HMM and run core algorithm ...
Warning: using 1 for genotyping.
Write results to VCF ...

###### Summary ######
time spent reading input files: 0.172345 sec
time spent counting kmers:      72.0957 sec
time spent selecting paths:     0.00323378 sec
time spent determining unique kmers:    0.25496 sec
time spent genotyping chromosome chr1:  0.304912
total running time:     72.9184 sec
total wallclock time: 72.6206 sec
Total maximum memory usage: 48.4737 GB
```
I suspect there is a 62GB memory limit, and running the EVG process takes up a portion of it. This leads to insufficient memory when running the PanGenie module. After all, even when running PanGenie separately without processing the reference, it still requires 48GB of memory？
Is it possible for EVG to split the processing of relatively large fastq files and the genome into two steps when running the PanGenie module? Namely, a Preprocessing step and a Genotyping step in PanGenie Manual. Running a single command directly consumes too much memory.
Finally, please forgive me for closing the previous question without expressing my gratitude. I'm truly sorry, and I want to take this opportunity to say thank you once again.

**Comment by duzezhen** [comment]
Glad to know you resolved the error.

Your suggestions regarding the `PanGenie` task submission logic were truly great. We have improved it in `v1.0.9`.

However, based on our test data, the peak memory usage was only 24GB. Therefore, we are not sure why you encountered insufficient memory. You could try using `"--jobs 1"` to limit the parallelization of the software to one job, which might reduce memory consumption.

Thank you again for your valuable feedback.

**Comment by YiBenqiu** [comment]
Thank you for updating EVG. However, we noticed that after installation, the version of the PanGenie software is still not the latest, meaning it lacks the '-f' parameter.

**Comment by duzezhen** [comment]
Yes, since the highest version of `PanGenie` available on conda is **2.1.0**, you need to remove the existing `PanGenie` package from your conda environment and manually compile the latest version of `PanGenie`. Furthermore, we have just released **version 1.1.0**, which fixes the issue with `PanGenie` index path generation.

**Comment by YiBenqiu** [comment]
Thank you for your prompt response. I will install the updated version you provided. If there are any further issues, I will provide feedback promptly.

**Comment by duzezhen** [comment]
Thank you for your feedback and suggestions!
