### ISSUE TITLE
multiple variants observed, skip this stie

### ISSUE THREAD

**Issue by YiBenqiu** [JiaoLab2021/EVG#3]
Description:
Hello, we have noticed that during the use of EVG, when converting VCF files with graphvcf, it tends to filter out SVs with overlapping positions. 
![微信图片_20231025114905](https://github.com/JiaoLab2021/EVG/assets/57091259/cea4488b-4f41-4305-9ec3-176065f9111d)
Here is an example of the first filtered site. We found that there are two types of SVs present simultaneously at this site. Therefore, is it reasonable to directly filter out this site? Could we consider retaining it?

![cc9233c69b6060680c7756e2d676cf8](https://github.com/JiaoLab2021/EVG/assets/57091259/0f7fa94a-8649-418f-8da3-0db9f8b39e46)

**Comment by YiBenqiu** [comment]
![image](https://github.com/JiaoLab2021/EVG/assets/57091259/f727b181-8525-4f5b-8827-fcde0c32cab7)
I'm sorry, but I'm not familiar with C language. I speculate that this section of code may be the one in effect. Therefore, can I comment out this section of code and recompile the EVG software?

**Comment by duzezhen** [comment]
I apologize for the delayed response. `EVG` implemented this process because some software may encounter errors when encountering the same coordinates. If you wish to bypass this filtering condition, you can comment out **lines 437-443** and recompile.

**Comment by YiBenqiu** [comment]
Hello, following your advice, I commented out this section of code, recompiled it, and ran the script again. I found that convert.test.vcf.gz only retains the first SV in the SVs with overlapping positions.

**Comment by duzezhen** [comment]
Does running the `graphvcf convert` command now produce no "multiple variants observed, skip this site" messages?

<img width="957" alt="image" src="https://github.com/JiaoLab2021/EVG/assets/54875184/3f18f6eb-6dd3-4b78-b9d4-e95f7da2c81b">

There is still a deduplication script in the `convert.py` script at lines 363-367. You can modify it as follows:

```
cmd += '''mv {} {}'''.format(
        vcf_out_name + ".sort",
        vcf_out_name
    )
```

This will allow duplicate variants to be retained. However, please note that if Paragraph and PanGenie software are used downstream, errors may occur.

In fact, overlapping coordinates should be a problem with the variant merging software.
