### ISSUE TITLE
老师，请问这个软件适合在动物上使用吗？

### ISSUE THREAD

**Issue by jinhua2024** [JiaoLab2021/EVG#7]
老师，我正在做猪的SV基因分型，请问这个软件是否可以适合呢？

**Comment by duzezhen** [comment]
您好，虽然我们没在动物基因组上进行测试，但理论上是适用的。结合多个软件的证据是可以提高分型准确性的。

**Comment by jinhua2024** [comment]
好的，谢谢您的解答！

**Comment by jinhua2024** [comment]
杜老师，怎么准备输入fastq文件？evg程序自带质控吗？还是先对下机测序数据先fastp质控，再作为输入？另外同一个样本的fastq测序数据有不同lane,这个该怎么处理呢？是先合并吗？谢谢您！

**Comment by duzezhen** [comment]
您好，EVG没有质控步骤的，所以要先对数据质控再用于下游分析。

同一个样本多个fastq文件要先合并。双端测序合并过程中要注意文件顺序保持一致。

`
cat file1.1.fq.gz file2.1.fq.gz > merge.1.fq.gz
`
`
cat file1.2.fq.gz file2.2.fq.gz > merge.2.fq.gz
`

**Comment by jinhua2024** [comment]
谢谢杜老师！！

**Comment by jinhua2024** [comment]
杜老师，再咨询一下，输入的fastq文件需要去除重复吧？就是质控--去除重复--再作为输入。谢谢杜老师！

**Comment by jinhua2024** [comment]
杜老师，请问输入vcf文件的格式是怎么样的？我运行EVG时报错了,[read::2024-08-26 03:17:48] Error: '/osmgfs10000/home/wujinhua/assembly/assembly_PAV/ANALYSIS/large_50bp/2024paragraph/20240729NC_AR_asmine_merge11_11100_no_samples.vcf' -> The number of vcf columns is less than 9.
我的vcf文件只保留这8列，#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
我把样本信息列（format）删除了，是否添加format和样本名称就可以了？修改为以下格式
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	D2

**Comment by duzezhen** [comment]
您好，输入的VCF文件中要有分型信息，您可以参考下示例数据中的文件：`https://github.com/JiaoLab2021/EVG/blob/main/test/test.vcf.gz`。

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1    sample2     ...     sampleN

**Comment by jinhua2024** [comment]
杜老师，这是您的vcf文件示例
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sim
chr1	253	SNP2	T	C	.	PASS	END=253;SVLEN=0;SVTYPE=SNP	GT	1|1
其中，sim是样本名称，基因型那个是1|1，请问在输入文件中，sim的基因型对输出结果有影响吗？
另外输入文件的基因型表示方式可以是1/1吗？
谢谢杜老师！

**Comment by jinhua2024** [comment]
杜老师，最后merge生成的文件夹，同一个样本有连个vcf.gz文件。如sampleA.vcf.gz和h.sampleA.vcf.gz,请问他们有什么区别呢？可能是一种筛选，但我不知道根据什么进行筛选

**Comment by duzezhen** [comment]
您好，一般情况下用sampleA.vcf.gz文件就行。

如果可以确保基因组图中有与sampleA非常相似的样本，那么就选择h.sampleA.vcf.gz文件，可以在一定程度上提升分型准确性。

**Comment by duzezhen** [comment]
一般情况下用sampleA.vcf.gz文件就可以的。

如果能确保基因组图中有与样本A相似的基因组，那么用h.sampleA.vcf.gz可以提高分型的准确性。

**Comment by jinhua2024** [comment]
谢谢杜老师！我第一次运行9个样本有成功运行出来的merge，但是我第二次运行其他样本，我又遇到新问题。
        报错1
Error occurred with status code: 1. Error message: [2024-08-29 23:48:28.038] <error> hts_parallel_reader.cpp:309 Reads with name=FP200008885L1C080R04706578436 both have IS_FIRST_IN_PAIR=1.
       报错2
        Error occurred with status code: 1. Error message: [2024-08-29 23:53:00.330] <error> hts_parallel_reader.cpp:309 Reads with name=FP200008885L1C080R04705557730 both have IS_FIRST_IN_PAIR=1.
       
      我的命令：conda activate EVG_env
EVG -r GCF_000003025.6_Sscrofa11.1_genomic.fna -v 20240729NC_AR_asmine_merge11_11100_no_samples.vcf -s FM_EVG_sample.list.txt --depth 30 --mode precise --threads 48 --restart

 其中，我本来FM_EVG_sample.list.txt里边包含了15个样本，后来命令停止运行，我以为是内存不够导致的。我就拆分FM_EVG_sample.list.txt里边为1个或2个样本进行运行。
 两次运行不同的样本，出现两次报错。可是例如我在bam文件中查找不到名为309 Reads with name=FP200008885L1C080R04705557730的read。
 上述报错的运行样本是不同lane测序产生的，用cat进行fastq合并，
 合并命令cat DP8450009337BR_L01_309_1_clean.fq.gz FP200008885_L01_309_1_clean.fq.gz > merge_309_1_clean.fq.gz

**Comment by duzezhen** [comment]
可能是您测序数据中read名字有问题，你在测序数据搜FP200008885L1C080R04706578436看下。

https://github.com/DecodeGenetics/graphtyper/issues/101
您可以参考这个issues，问题是一样的。

**Comment by jinhua2024** [comment]
谢谢杜老师，我在生成的bwa文件夹下的bam文件中找出来了。
FP200008885L1C080R04705557730	99	NC_010443.5	29776	60	150M	=	29958	332	ATTTAGGAATTAATTTTTGATACATAGATGTACCAAAGTTTAATCACTTCCCCGCTGGTGCGCATTTGGGTTGTGGGAGGGCCATTAAAATAATAGGTACACTGACATACAAGCAAATTTAGAGCCTGCCTTTGCAAACTTGCGTGAATA	H.0GHHGG0HC9>;/<B2H9DGI:.HIGHICH:IHB:CI-DDI/GGHH*GCII%B-HG*C%IHHDH:<>H.7=<I;H4I%ICFA-IG5>F6H6IAIIGIH@1H%IGE1HI2GHGGBH<8HF2,HI>D69AH:IFGC0:IC9A-G3H;?:C	NM:i:8	MD:Z:11T41T6G18A13C9T23T14T7	MC:Z:150M	MQ:i:60	AS:i:110	XS:i:21	RG:Z:foo
FP200008885L1C080R04705557730	99	NC_010443.5	29776	60	150M	=	29958	332	ATTTAGGAATTAATTTTTGATACATAGATGTACCAAAGTTTAATCACTTCCCCGCTGGTGCGCATTTGGGTTGTGGGAGGGCCATTAAAATAATAGGTACACTGACATACAAGCAAATTTAGAGCCTGCCTTTGCAAACTTGCGTGAATA	H.0GHHGG0HC9>;/<B2H9DGI:.HIGHICH:IHB:CI-DDI/GGHH*GCII%B-HG*C%IHHDH:<>H.7=<I;H4I%ICFA-IG5>F6H6IAIIGIH@1H%IGE1HI2GHGGBH<8HF2,HI>D69AH:IFGC0:IC9A-G3H;?:C	NM:i:8	MD:Z:11T41T6G18A13C9T23T14T7	MC:Z:150M	MQ:i:60	AS:i:110	XS:i:21	RG:Z:foo
FP200008885L1C080R04705557730	147	NC_010443.5	29958	60	150M	=	29776	-332	GCCGAGTAAGGGGGCCACACATTCCAGTTTTGCCTAGTTACAGTAAATAGCCCTTCTAAAGCATTAGATCAGTGTACACTCTTTCCCAGTATCAGAGAGTTCCCATTTCCCACAACCTCACCAGTCATTGTTAGTCTAATATGTTAAAAT	+1D>2G'GAH)HBI%C9HH.)85.H:H@&7H3EFI>IHH%BA<:A7HEGHGBGGG;GIGGIIFGFIG:8/IHHI@8@@I0IGI8D3I;IHFEIH<HHGIH)G+HD:E,@4I@IGGGIEIH,IGI&H7HII;IDI:H(;HH.IG7FIGIGH	NM:i:7	MD:Z:0A9A3A8T7T68A23G25	MC:Z:150M	MQ:i:60	AS:i:119	XS:i:20	RG:Z:foo
FP200008885L1C080R04705557730	147	NC_010443.5	29958	60	150M	=	29776	-332	GCCGAGTAAGGGGGCCACACATTCCAGTTTTGCCTAGTTACAGTAAATAGCCCTTCTAAAGCATTAGATCAGTGTACACTCTTTCCCAGTATCAGAGAGTTCCCATTTCCCACAACCTCACCAGTCATTGTTAGTCTAATATGTTAAAAT	+1D>2G'GAH)HBI%C9HH.)85.H:H@&7H3EFI>IHH%BA<:A7HEGHGBGGG;GIGGIIFGFIG:8/IHHI@8@@I0IGI8D3I;IHFEIH<HHGIH)G+HD:E,@4I@IGGGIEIH,IGI&H7HII;IDI:H(;HH.IG7FIGIGH	NM:i:7	MD:Z:0A9A3A8T7T68A23G25	MC:Z:150M	MQ:i:60	AS:i:119	XS:i:20	RG:Z:foo
是怎么处理呢？直接删掉这四个reads吗？谢谢杜老师

**Comment by jinhua2024** [comment]
不同lane合并的测序数据中read名字有问题，这个我使用fastp解决了。另外，想请问一下，我用相同样本的的同一份二代测序数据，对不同的vcf文件进行基因分型，这个怎么解决呢？是否有好的方法避免继续运行前面两个步骤convert和bwa呢？谢谢杜老师！！

**Comment by duzezhen** [comment]
您好，可以使用 `--restart` 参数跳过某些步骤的。比如已经有了BAM文件，就可以在当前路径创建bwa文件夹，然后把BAM文件软连接到当前路径。

**Comment by jinhua2024** [comment]
谢谢杜老师！我跑了十几个样本，报错了。不知道为什么
[2024-09-02 21:56:37,239] [EVG.getsize] file exists, skip: graphtyper.vcf
[2024-09-02 21:56:37,240] [EVG.getsize] file exists, skip: graphtyper.vcf
Warning: BayesTyper does not generate any folders starting with 'bayestyper_unit_'.

“可以使用 --restart 参数跳过某些步骤的。比如已经有了BAM文件，就可以在当前路径创建bwa文件夹，然后把BAM文件软连接到当前路径“。
另外，建立软连接后， 这些参数可以修改吗？--depth 30 --mode precise 。因为--depth 30运行太久了呢

**Comment by duzezhen** [comment]
报错是因为genotype/BayesTyper文件夹内容不完整，您需要把这个文件夹删除了，重新运行。

--depth 30 --mode precise 可以修改。

**Comment by jinhua2024** [comment]
谢谢杜老师！

**Comment by jinhua2024** [comment]
杜老师，删除了，重跑一样的报错Warning: BayesTyper does not generate any folders starting with 'bayestyper_unit_'.
请问杜老师我是否指定其中两个软件跑，paragraph和VG两个工具，输出的结果是否也是这两个软件合并评估后的结果？

**Comment by duzezhen** [comment]
可以检查下运行内存消耗，BayesTyper需要的内存比较多。

是的，只指定paragraph和VG，输出的是这两个软件的结果。

**Comment by jinhua2024** [comment]
谢谢杜老师!EVG使用了8款软件，请问您有没有推荐的更高效，如其中的哪4款就获得比较好的效果。
我的结果输出只有4款软件：Paragraph，VG-Giraffe，GraphTyper2, BayesTyper
指定参数正确吗：--software vg map, vg giraffe, vg giraffe

**Comment by jinhua2024** [comment]
> 可以检查下运行内存消耗，BayesTyper需要的内存比较多。
> 
> 是的，只指定paragraph和VG，输出的是这两个软件的结果。

-我重新跑了evg，--depth 15，原来是--depth 30。结果还是一样的报错。可否指定排除某个软件的？比如BayesTyper

**Comment by jinhua2024** [comment]
> 可以检查下运行内存消耗，BayesTyper需要的内存比较多。
> 
> 是的，只指定paragraph和VG，输出的是这两个软件的结果。

-我重新跑了evg，--depth 15，原来是--depth 30。结果还是一样的报错。可否指定排除某个软件的？比如BayesTyper

**Comment by duzezhen** [comment]
您第一次是成功运行了的，目前尚不清楚BayesTyper报错的原因，看报错可能是有的文件生成不完整。

您可以直接用--software指定具体需要的软件，这样就可以排出BayesTyper的。

Paragraph、vg giraffe、GraphTyper、PanGenie软件的效果都是很好的。

**Comment by jinhua2024** [comment]
杜老师，我按照您说，构建convert和bwa文件夹中文件的软连接，使用--restart 参数，并不能省下不跑前面的流程。一样在convert文件生成新的fq.gz的文件。
[2024-09-15 15:58:53,705] /convert' already exists, using restart, skipping folder clearance.
[2024-09-15 15:58:53,705] 
[2024-09-15 15:58:53,705] ----------------------------------------------------------------- fastAQ count -----------------------------------------------------------------
[2024-09-15 15:58:53,707] CMD:envs/EVG_env/bin/fastAQ count -i /GCF_000003025.6_Sscrofa11.1_genomic.fna
[2024-09-15 15:59:04,389] 
[2024-09-15 15:59:04,389] ----------------------------------------------------------------- fastAQ sample -----------------------------------------------------------------
[2024-09-15 15:59:04,425] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_315_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_315_2_clean.fq.gz
[2024-09-15 15:59:04,478] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_2_clean.fq.gz
[2024-09-15 15:59:04,529] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_317_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_317_2_clean.fq.gz
[2024-09-15 15:59:04,578] CMD:envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_318_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_318_2_clean.fq.gz
[2024-09-15 15:59:04,631] CMD:envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_320_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_320_2_clean.fq.gz
[2024-09-15 15:59:04,680] CMD:envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_321_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_321_2_clean.fq.gz
[2024-09-15 15:59:04,738] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001055TL_L01_324_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001055TL_L01_324_2_clean.fq.gz
[2024-09-15 15:59:04,787] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001075BL_L01_323_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001075BL_L01_323_2_clean.fq.gz
[2024-09-15 15:59:04,833] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/merge_314_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/merge_314_2_clean.fq.gz
[2024-09-15 16:28:39,387] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_2_clean.fq.gz -f 0.59 2>/dev/stderr | gzip > /convert/sample.0.59.FP150001004BR_L01_316_2_clean.fq.gz
[2024-09-15 16:28:39,389] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_1_clean.fq.gz -f 0.59 2>/dev/stderr | gzip > /convert/sample.0.59.FP150001004BR_L01_316_1_clean.fq.gz
[2024-09-15 16:29:05,992] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/merge_314_1_clean.fq.gz -f 0.593 2>/dev/stderr | gzip > /convert/sample.0.593.merge_314_1_clean.fq.gz
[2024-09-15 16:29:05,995] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/merge_314_2_clean.fq.gz -f 0.593 2>/dev/stderr | gzip > /convert/sample.0.593.merge_314_2_clean.fq.gz

**Comment by jinhua2024** [comment]
杜老师，新生成fastq文件是因为--depth 使用的参数不一样。但是就算更改--depth 参数，bam文件还是没有新生成的，bam文件还是以前的文件。
--software Paragraph --software VG-Giraffe --software PanGenie --software GraphTyper2
我命令使用了4个软件。但是genotype只有GraphTyper2的结果，输出的vcf也是没有其他三个。请问杜老师指定多个软件怎么设置，是我这样吗？

**Comment by duzezhen** [comment]
> 杜老师，我按照您说，构建convert和bwa文件夹中文件的软连接，使用--restart 参数，并不能省下不跑前面的流程。一样在convert文件生成新的fq.gz的文件。 [2024-09-15 15:58:53,705] /convert' already exists, using restart, skipping folder clearance. [2024-09-15 15:58:53,705] [2024-09-15 15:58:53,705] ----------------------------------------------------------------- fastAQ count ----------------------------------------------------------------- [2024-09-15 15:58:53,707] CMD:envs/EVG_env/bin/fastAQ count -i /GCF_000003025.6_Sscrofa11.1_genomic.fna [2024-09-15 15:59:04,389] [2024-09-15 15:59:04,389] ----------------------------------------------------------------- fastAQ sample ----------------------------------------------------------------- [2024-09-15 15:59:04,425] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_315_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_315_2_clean.fq.gz [2024-09-15 15:59:04,478] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_2_clean.fq.gz [2024-09-15 15:59:04,529] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_317_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_317_2_clean.fq.gz [2024-09-15 15:59:04,578] CMD:envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_318_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_318_2_clean.fq.gz [2024-09-15 15:59:04,631] CMD:envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_320_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_320_2_clean.fq.gz [2024-09-15 15:59:04,680] CMD:envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_321_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_321_2_clean.fq.gz [2024-09-15 15:59:04,738] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001055TL_L01_324_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001055TL_L01_324_2_clean.fq.gz [2024-09-15 15:59:04,787] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/FP150001075BL_L01_323_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/FP150001075BL_L01_323_2_clean.fq.gz [2024-09-15 15:59:04,833] CMD: envs/EVG_env/bin/fastAQ count -i /W230130010/all_fastp/fastp20240824/merge_314_1_clean.fq.gz -i /W230130010/all_fastp/fastp20240824/merge_314_2_clean.fq.gz [2024-09-15 16:28:39,387] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_2_clean.fq.gz -f 0.59 2>/dev/stderr | gzip > /convert/sample.0.59.FP150001004BR_L01_316_2_clean.fq.gz [2024-09-15 16:28:39,389] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/FP150001004BR_L01_316_1_clean.fq.gz -f 0.59 2>/dev/stderr | gzip > /convert/sample.0.59.FP150001004BR_L01_316_1_clean.fq.gz [2024-09-15 16:29:05,992] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/merge_314_1_clean.fq.gz -f 0.593 2>/dev/stderr | gzip > /convert/sample.0.593.merge_314_1_clean.fq.gz [2024-09-15 16:29:05,995] CMD: envs/EVG_env/bin/fastAQ sample -i /W230130010/all_fastp/fastp20240824/merge_314_2_clean.fq.gz -f 0.593 2>/dev/stderr | gzip > /convert/sample.0.593.merge_314_2_clean.fq.gz

如果更改了`--depth`参数，`convert`文件夹里的`fq.gz`文件名会变动，所以会生成新的`fq.gz`文件。

**Comment by duzezhen** [comment]
> 杜老师，新生成fastq文件是因为--depth 使用的参数不一样。但是就算更改--depth 参数，bam文件还是没有新生成的，bam文件还是以前的文件。 --software Paragraph --software VG-Giraffe --software PanGenie --software GraphTyper2 我命令使用了4个软件。但是genotype只有GraphTyper2的结果，输出的vcf也是没有其他三个。请问杜老师指定多个软件怎么设置，是我这样吗？

`--software`参数提交的是一个列表，应将代码更改为：`--software Paragraph VG-Giraffe PanGenie GraphTyper2`。

**Comment by jinhua2024** [comment]
> 一般情况下用sampleA.vcf.gz文件就可以的。
> 
> 如果能确保基因组图中有与样本A相似的基因组，那么用h.sampleA.vcf.gz可以提高分型的准确性。

杜老师，我使用了--software Paragraph VG-Giraffe GraphTyper2参数。不太明白这两个结果的区别。因为sampleA.vcf.gz输出结果我变异位点较少。而h.sampleA.vcf.gz会更多。因为我想要看我输入的vcf文件中的位点，在这些样本中的SV是怎么样的。不太明白这个确保基因组图中有与样本A相似的基因组。输出的结果大多数是GraphTyper2软件的结果。谢谢杜老师解惑！
NC_010443.5	47129461	0_NC_010443.5-47129462-DEL-53	CAAGAAATACAACAACAACAACAACAAAAGACAAAAGACAAATAAATAAATAAA	C	.	.	ID=NC_010443.5-47129462-DEL-53;SVTYPE=DEL;TIG_REGION=h1tg000006l:39088596-39088596;QUERY_STRAND=+;HOM_REF=0,0;HOM_TIG=0,0;END=47129514;STARTVARIANCE=0.000000;ENDVARIANCE=0.000000;AVG_LEN=-53.000000;AVG_START=47129461.000000;AVG_END=47129514.000000;SUPP_VEC_EXT=11110;IDLIST_EXT=NC_010443.5-47129462-DEL-53,NC_010443.5-47129462-DEL-53,NC_010443.5-47129462-DEL-53,NC_010443.5-47129462-DEL-53;SUPP_EXT=4;SUPP_VEC=11110;SUPP=4;SVMETHOD=JASMINE;IDLIST=NC_010443.5-47129462-DEL-53,NC_010443.5-47129462-DEL-53,NC_010443.5-47129462-DEL-53,NC_010443.5-47129462-DEL-53	GT:SO:DP:ADP:NDP	0/1:GraphTyper2:0.044:13.60:17.00

**Comment by duzezhen** [comment]
比如您构建基因组图的变异分别来自于`亚种A`和`亚种B`，如果`sampleA`为`亚种A`，就可以直接使用`h.xx.vcf.gz`的结果。如果`sampleA`不属于`亚种A`和`亚种B`，那么应该使用`xx.vcf.gz`的结果。

上述过程需要知道待分型样本的种群分布信息，如果该信息不全或不精确，那么所有样本都应使用`xx.vcf.gz`的结果。

**Comment by jinhua2024** [comment]
我的数据是来自同一个品种，都是猪，同一个品系。那就用h开头的，是这样子吗？另外，输出结果的有软件的优先级吗？大多数结果都由同一个软件输出



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ze-Zhen Du ***@***.***&gt;
发送时间: 2024年9月23日 23:10
收件人: JiaoLab2021/EVG ***@***.***&gt;
抄送: jinhua2024 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [JiaoLab2021/EVG] 老师，请问这个软件适合在动物上使用吗？ (Issue #7)





 
比如您构建基因组图的变异分别来自于亚种A和亚种B，如果sampleA为亚种A，就可以直接使用h.xx.vcf.gz的结果。如果sampleA不属于亚种A和亚种B，那么应该使用xx.vcf.gz的结果。
 
上述过程需要知道待分型样本的种群分布信息，如果该信息不全或不精确，那么所有样本都应使用xx.vcf.gz的结果。

**Comment by duzezhen** [comment]
EVG输出的软件名字是在当前位点，该软件的概率最大。

**Comment by jinhua2024** [comment]
杜老师，因为我需要比较准确的分型结果，EVG输出的结果还需要进行过滤吗？还是说EVG就已经进行了过滤不确定的分型结果。
这是h.sampleA.vcf.gz我输出的部分位点结果。
GT:SO:DP:ADP:NDP	1/1:PanGenie:0.39:13.9:16	1/1:PanGenie:1.925:12.15:22	0/1:VG-Giraffe:-0.62:18.13:14	1/1:PanGenie:1.427:14.03:22	1/1:PanGenie:-0.56:13.24:10	1/1:PanGenie:1.426:13.64:22	1/1:PanGenie:0.055:13.69:14	1/1:PanGenie:0.358:12.18:14	1/1:PanGenie:4.576:13.2:36
GT:SO:DP:ADP:NDP   1/1:GraphTyper2:-0.14:15.24:14	1/1:GraphTyper2:0.148:12.95:14	1/1:GraphTyper2:-0.32:14.52:12	1/1:GraphTyper2:-0.41:15.28:12	1/1:GraphTyper2:-0.1:14.93:14	1/1:GraphTyper2:-0.77:14.39:8	1/1:GraphTyper2:0.171:14.62:16	1/1:GraphTyper2:-0.39:12.77:10	1/1:GraphTyper2:0.774:14.26:20
GT:SO:DP:ADP:NDP   0/1:GraphTyper2:1.029:15.24:24	./.:.:.:.:.	1/1:GraphTyper2:1.727:14.52:28	1/1:GraphTyper2:3.124:15.28:40	0/1:GraphTyper2:1.292:14.93:26	0/1:GraphTyper2:-0.41:14.39:11	0/1:GraphTyper2:0.919:14.62:22	0/1:GraphTyper2:0.031:12.77:13	1/1:GraphTyper2:3.205:14.26:38

**Comment by duzezhen** [comment]
不用再过滤了。

**Comment by jinhua2024** [comment]
杜老师好！我正在使用EVG输出端结果指定了几款软件。但是h.sampleA.vcf.gz输出端结果有问题，示例如下：
merge文件夹的h.sampleA.vcf.gz的结果基因型为0/0
NC_010455.5	204624599	>53010745>53010748	T	C	60.0	.	AC=5;AF=0.333333;NS=10;AN=15;LV=0;AT=>53010745>53010747>53010748,>53010745>53010746>53010748;SVTYPE=SNP;END=204624599	GT:SO:DP:ADP:NDP	0/0:VG-Giraffe:-0.56:19.30:15.00
然而genotype文件夹的各款软件的该位点并不是0/0
VG-Giraffe：
NC_010455.5	204624599	>14969322>14969325	T	C	126.559	PASS	AT=>14969322>14969324>14969325,>14969322>14969323>14969325;DP=14	GT:DP:AD:GL:GQ:GP:XD:MAD	1/0:14:7,7:-13.870150,-1.691374,-13.870150:121:-1.098612:14.696428:7
pangenie：
NC_010455.5	204624599	.	T	C	.	PASS	AF=0.25;UK=68;MA=0	GT:GQ:GL:KC	0/1:10000:-79.7579,0,-61.87:10
GraphAligner:
NC_010455.5	204624599	>53731816>53731819	T	C	67.4721	PASS	AT=>53731816>53731818>53731819,>53731816>53731817>53731819;DP=11	GT:DP:AD:GL:GQ:GP:XD:MAD	0/1:11:7,4:-8.031929,-1.761825,-14.968464:62:-1.098613:12.089286:4
不清楚什么原因

**Comment by jinhua2024** [comment]
杜老师，如果软件指定vg和pangenie，EVG可以处理vcf文件中多等位sv的基因分型吗？如果是多等位indel或snp呢？谢谢杜老师！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ze-Zhen Du ***@***.***&gt;
发送时间: 2024年9月30日 16:50
收件人: JiaoLab2021/EVG ***@***.***&gt;
抄送: jinhua2024 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [JiaoLab2021/EVG] 老师，请问这个软件适合在动物上使用吗？ (Issue #7)





 
不用再过滤了。
