### ISSUE TITLE
What is the difference between h.sample.vcf.gz and sample.vcf.gz in merge/ folder

### ISSUE THREAD

**Issue by zhixue** [JiaoLab2021/EVG#9]
Hello, thanks for your wonderful work.

I noted that 'h.sample.vcf.gz' existed in merge/ folder, which was larger (file size) than 'sample.vcf.gz'.

Maybe it was generated with only one sample in '-s sample.txt', or other reasons? There are no description about it in README or WIKI.

Could you tell me the difference between h.sample.vcf.gz and sample.vcf.gz?

**Comment by duzezhen** [comment]
If your input population VCF file contains samples `A`, `B`, `C`, `D`, and `E`, and `sample B` is most similar to `sample`, then `h.sample.vcf.gz` is generated by performing genotyping specifically for `sample B` and outputting the genotyped results. This strategy can improve genotyping accuracy when similar samples are present.

In most cases, you can simply use the genotyping results in `sample.vcf.gz`. The `h.sample.vcf.gz` file is only relevant when there is a sample in the population VCF that is highly similar to the sample.

**Comment by zhixue** [comment]
That is useful information when evaluting samples with both short reads and long reads data.

Thanks for your reply again : )
